joint_limits:
  right_finger_bottom_joint:
    min_position: 0.0 # -0.09
    max_position: 0.85
    max_velocity: 0.6
    max_effort: 1000.0
    damping: 0.7
    friction: 1.0
  right_finger_tip_joint:
    min_position: -0.50 # -0.50, -1.03
    max_position: 0.21
    max_velocity: 1000.0
    max_effort: 1000.0
    damping: 0.7
    friction: 1.0
  left_finger_bottom_joint:
    # min_position: -0.85
    # max_position: 0.09
    min_position: 0.0 # -0.09
    max_position: 0.85
    max_velocity: 1000.0
    max_effort: 1000.0
    damping: 0.7
    friction: 1.0
  left_finger_tip_joint:
    min_position: -0.50 # -0.50, -1.03
    max_position: 0.21
    max_velocity: 1000.0
    max_effort: 1000.0
    damping: 0.7
    friction: 1.0